lang_script_code_to_name_map = {
    'ace_Arab': 'Acehnese (Jawi script)',
    'ace_Latn': 'Acehnese (Latin script)',
    'acm_Arab': 'Mesopotamian Arabic',
    'acq_Arab': 'Taʽizzi-Adeni Arabic',
    'aeb_Arab': 'Tunisian Arabic',
    'afr_Latn': 'Afrikaans',
    'ajp_Arab': 'South Levantine Arabic',
    'aka_Latn': 'Akan',
    'als_Latn': 'Albanian (Tosk)',
    'amh_Ethi': 'Amharic',
    'apc_Arab': 'Levantine Arabic',
    'apc_Arab_nort3139': 'North Levantine Arabic',
    'apc_Arab_sout3123': 'South Levantine Arabic',
    'arb_Arab': 'Modern Standard Arabic',
    'arb_Latn': 'Modern Standard Arabic (Romanized)',
    'arg_Latn': 'Aragonese',
    'ars_Arab': 'Najdi Arabic',
    'ary_Arab': 'Moroccan Arabic',
    'arz_Arab': 'Egyptian Arabic',
    'asm_Beng': 'Assamese',
    'ast_Latn': 'Asturian',
    'awa_Deva': 'Awadhi',
    'ayr_Latn': 'Central Aymara',
    'azb_Arab': 'South Azerbaijani',
    'azj_Latn': 'North Azerbaijani',
    'bak_Cyrl': 'Bashkir',
    'bam_Latn': 'Bambara',
    'ban_Latn': 'Balinese',
    'bel_Cyrl': 'Belarusian',
    'bem_Latn': 'Bemba',
    'ben_Beng': 'Bengali',
    'ben_Latn': 'Bengali (Latin script)',
    'bho_Deva': 'Bhojpuri',
    'bjn_Arab': 'Banjar (Jawi script)',
    'bjn_Latn': 'Banjar (Latin script)',
    'bod_Tibt': 'Lhasa Tibetan',
    'bos_Latn': 'Bosnian',
    'brx_Deva': 'Bodo',
    'bug_Latn': 'Buginese',
    'bul_Cyrl': 'Bulgarian',
    'cat_Latn': 'Valencian',
    'ceb_Latn': 'Cebuano',
    'ces_Latn': 'Czech',
    'chv_Cyrl': 'Chuvash',
    'cjk_Latn': 'Chokwe',
    'ckb_Arab': 'Central Kurdish',
    'cmn_Hans': 'Simplified Chinese',
    'cmn_Hant': 'Traditional Chinese',
    'crh_Latn': 'Crimean Tatar',
    'cym_Latn': 'Welsh',
    'dan_Latn': 'Danish',
    'dar_Cyrl': 'Dargwa',
    'deu_Latn': 'German',
    'dgo_Deva': 'Dogri',
    'dik_Latn': 'Southwestern Dinka',
    'dyu_Latn': 'Dyula',
    'dzo_Tibt': 'Dzongkha',
    'ekk_Latn': 'Estonian',
    'ell_Grek': 'Greek',
    'eng_Latn': 'English',
    'epo_Latn': 'Esperanto',
    'est_Latn': 'Estonian',
    'eus_Latn': 'Basque',
    'ewe_Latn': 'Ewe',
    'fao_Latn': 'Faroese',
    'fij_Latn': 'Fijian',
    'fil_Latn': 'Filipino',
    'fin_Latn': 'Finnish',
    'fon_Latn': 'Fon',
    'fra_Latn': 'French',
    'fur_Latn': 'Friulian',
    'fuv_Latn': 'Nigerian Fulfulde',
    'gaz_Latn': 'West Central Oromo',
    'gla_Latn': 'Scottish Gaelic',
    'gle_Latn': 'Irish',
    'glg_Latn': 'Galician',
    'gom_Deva': 'Goan Konkani',
    'grn_Latn': 'Guarani',
    'gug_Latn': 'Paraguayan Guaraní',
    'guj_Gujr': 'Gujarati',
    'hat_Latn': 'Haitian Creole',
    'hau_Latn': 'Hausa',
    'heb_Hebr': 'Hebrew',
    'hin_Deva': 'Hindi',
    'hin_Latn': 'Hindi (Latin script)',
    'hne_Deva': 'Chhattisgarhi',
    'hrv_Latn': 'Croatian',
    'hun_Latn': 'Hungarian',
    'hye_Armn': 'Armenian',
    'ibo_Latn': 'Igbo',
    'ilo_Latn': 'Ilocano',
    'ind_Latn': 'Indonesian',
    'isl_Latn': 'Icelandic',
    'ita_Latn': 'Italian',
    'jav_Latn': 'Javanese',
    'jpn_Jpan': 'Japanese',
    'kaa_Latn': 'Karakalpak',
    'kab_Latn': 'Kabyle',
    'kac_Latn': 'Jingpho',
    'kam_Latn': 'Kamba',
    'kan_Knda': 'Kannada',
    'kas_Arab': 'Kashmiri (Arabic script)',
    'kas_Deva': 'Kashmiri (Devanagari script)',
    'kat_Geor': 'Georgian',
    'kaz_Cyrl': 'Kazakh',
    'kbp_Latn': 'Kabiyè',
    'kea_Latn': 'Kabuverdianu',
    'khk_Cyrl': 'Mongolian',
    'khm_Khmr': 'Khmer',
    'kik_Latn': 'Kikuyu',
    'kin_Latn': 'Kinyarwanda',
    'kir_Cyrl': 'Kyrgyz',
    'kmb_Latn': 'Kimbundu',
    'kmr_Latn': 'Northern Kurdish',
    'knc_Arab': 'Central Kanuri (Arabic script)',
    'knc_Latn': 'Central Kanuri (Latin script)',
    'kon_Latn': 'Kikongo',
    'kor_Hang': 'Korean',
    'ktu_Latn': 'Kituba (DRC)',
    'lao_Laoo': 'Lao',
    'lij_Latn': 'Ligurian (Genoese)',
    'lim_Latn': 'Limburgish',
    'lin_Latn': 'Lingala',
    'lit_Latn': 'Lithuanian',
    'lld_Latn': 'Ladin (Val Badia)',
    'lmo_Latn': 'Lombard',
    'ltg_Latn': 'Latgalian',
    'ltz_Latn': 'Luxembourgish',
    'lua_Latn': 'Luba-Kasai',
    'lug_Latn': 'Ganda',
    'luo_Latn': 'Luo',
    'lus_Latn': 'Mizo',
    'lvs_Latn': 'Standard Latvian',
    'mag_Deva': 'Magahi',
    'mai_Deva': 'Maithili',
    'mal_Mlym': 'Malayalam',
    'mar_Deva': 'Marathi',
    'mhr_Cyrl': 'Meadow Mari',
    'min_Arab': 'Minangkabau (Jawi script)',
    'min_Latn': 'Minangkabau (Latin script)',
    'mkd_Cyrl': 'Macedonian',
    'mlt_Latn': 'Maltese',
    'mni_Beng': 'Meitei (Manipuri, Bengali script)',
    'mni_Mtei': 'Meitei (Manipuri, Meitei script)',
    'mos_Latn': 'Mossi',
    'mri_Latn': 'Maori',
    'mya_Mymr': 'Burmese',
    'myv_Cyrl': 'Erzya',
    'nld_Latn': 'Dutch',
    'nno_Latn': 'Norwegian Nynorsk',
    'nob_Latn': 'Norwegian Bokmål',
    'npi_Deva': 'Nepali',
    'npi_Latn': 'Nepali (Latin script)',
    'nqo_Nkoo': 'Nko',
    'nso_Latn': 'Northern Sotho',
    'nus_Latn': 'Nuer',
    'nya_Latn': 'Nyanja',
    'oci_Latn': 'Aranese',
    'ory_Orya': 'Odia',
    'pag_Latn': 'Pangasinan',
    'pan_Guru': 'Panjabi',
    'pap_Latn': 'Papiamento',
    'pbt_Arab': 'Southern Pashto',
    'pes_Arab': 'Western Persian',
    'plt_Latn': 'Plateau Malagasy',
    'pol_Latn': 'Polish',
    'por_Latn': 'Portuguese',
    'prs_Arab': 'Dari',
    'quy_Latn': 'Ayacucho Quechua',
    'ron_Latn': 'Romanian',
    'run_Latn': 'Rundi',
    'rus_Cyrl': 'Russian',
    'sag_Latn': 'Sango',
    'san_Deva': 'Sanskrit',
    'sat_Olck': 'Santali',
    'scn_Latn': 'Sicilian',
    'shn_Mymr': 'Shan',
    'sin_Latn': 'Sinhala (Latin script)',
    'sin_Sinh': 'Sinhala',
    'slk_Latn': 'Slovak',
    'slv_Latn': 'Slovenian',
    'smo_Latn': 'Samoan',
    'sna_Latn': 'Shona',
    'snd_Arab': 'Sindhi (Arabic script)',
    'snd_Deva': 'Sindhi (Devanagari script)',
    'som_Latn': 'Somali',
    'sot_Latn': 'Southern Sotho',
    'spa_Latn': 'Spanish',
    'srd_Latn': 'Sardinian',
    'srp_Cyrl': 'Serbian',
    'ssw_Latn': 'Swati',
    'sun_Latn': 'Sundanese',
    'swe_Latn': 'Swedish',
    'swh_Latn': 'Swahili',
    'szl_Latn': 'Silesian',
    'tam_Taml': 'Tamil',
    'taq_Latn': 'Tamasheq (Latin script)',
    'taq_Tfng': 'Tamasheq (Tifinagh script)',
    'tat_Cyrl': 'Tatar',
    'tel_Telu': 'Telugu',
    'tgk_Cyrl': 'Tajik',
    'tgl_Latn': 'Tagalog',
    'tha_Thai': 'Thai',
    'tir_Ethi': 'Tigrinya',
    'tpi_Latn': 'Tok Pisin',
    'tsn_Latn': 'Tswana',
    'tso_Latn': 'Tsonga',
    'tuk_Latn': 'Turkmen',
    'tum_Latn': 'Tumbuka',
    'tur_Latn': 'Turkish',
    'twi_Latn': 'Asante Twi',
    'tyv_Cyrl': 'Tuvan',
    'tzm_Tfng': 'Central Atlas Tamazight',
    'uig_Arab': 'Uyghur',
    'ukr_Cyrl': 'Ukrainian',
    'umb_Latn': 'Umbundu',
    'urd_Arab': 'Urdu',
    'urd_Latn': 'Urdu (Latin script)',
    'uzn_Latn': 'Northern Uzbek',
    'vec_Latn': 'Venetian',
    'vie_Latn': 'Vietnamese',
    'vmw_Latn': 'Emakhuwa (Central)',
    'war_Latn': 'Waray',
    'wol_Latn': 'Wolof',
    'wuu_Hans': 'Wu Chinese',
    'xho_Latn': 'Xhosa',
    'ydd_Hebr': 'Eastern Yiddish',
    'yor_Latn': 'Yoruba',
    'yue_Hant': 'Yue Chinese (Hong Kong Cantonese)',
    'zgh_Tfng': 'Standard Moroccan Tamazight',
    'zho_Hans': 'Simplified Chinese',
    'zho_Hant': 'Traditional Chinese',
    'zsm_Latn': 'Standard Malay',
    'zul_Latn': 'Zulu',

    'mfe_Latn': 'Mauritian Creole',
    'uzs_Arab': 'Southern Uzbek',
}

########## TWO LETTER CODES ##########

lang_two_letter_code_to_name_map = {
    'am': 'Amharic',
    'ar': 'Arabic',
    'as': 'Assamese',
    'bn': 'Bengali',
    'cs': 'Czech',
    'da': 'Danish',
    'de': 'German',
    'el': 'Greek',
    'en': 'English',
    'es': 'Spanish',
    'fa': 'Persian',
    'fi': 'Finnish',
    'fil': 'Filipino',
    'fr': 'French',
    'gu': 'Gujarati',
    'ha': 'Hausa',
    'he': 'Hebrew',
    'hi': 'Hindi',
    'hu': 'Hungarian',
    'id': 'Indonesian',
    'ig': 'Igbo',
    'it': 'Italian',
    'ja': 'Japanese',
    'km': 'Khmer',
    'kn': 'Kannada',
    'ko': 'Korean',
    'ky': 'Kyrgyz',
    'lt': 'Lithuanian',
    'mg': 'Malagasy',
    'ml': 'Malayalam',
    'mr': 'Marathi',
    'ms': 'Malay',
    'my': 'Burmese',
    'ne': 'Nepali',
    'nl': 'Dutch',
    'no': 'Norwegian',
    'ny': 'Chichewa',
    'or': 'Oriya',
    'pa': 'Punjabi',
    'pl': 'Polish',
    'pt': 'Portuguese',
    'ro': 'Romanian',
    'ru': 'Russian',
    'si': 'Sinhala',
    'sn': 'Shona',
    'so': 'Somali',
    'sr': 'Serbian',
    'sv': 'Swedish',
    'sw': 'Swahili',
    'ta': 'Tamil',
    'te': 'Telugu',
    'th': 'Thai',
    'tr': 'Turkish',
    'uk': 'Ukrainian',
    'vi': 'Vietnamese',
    'yo': 'Yoruba',
    'zh': 'Simplified Chinese',
    'zh_cn': 'Simplified Chinese',
    'zh_hk': 'Hong Kong Chinese',
    'zh_tw': 'Traditional Chinese'
}

########## THREE LETTER CODES ##########

lang_three_letter_code_to_name_map = {
    'afr': 'Afrikaans',
    'amh': 'Amharic',
    'ara': 'Arabic',
    'asm': 'Assamese',
    'aym': 'Aymara',
    'aze': 'Azerbaijani',
    'bem': 'Bemba',
    'ben': 'Bengali',
    'bod': 'Tibetan',
    'bos': 'Bosnian',
    'bul': 'Bulgarian',
    'cat': 'Catalan',
    'ces': 'Czech',
    'cym': 'Welsh',
    'deu': 'German',
    'ell': 'Greek',
    'eng': 'English',
    'epo': 'Esperanto',
    'ewe': 'Ewe',
    'fas': 'Persian',
    'fil': 'Filipino',
    'fon': 'Fon',
    'fra': 'French',
    'gla': 'Scottish Gaelic',
    'gle': 'Irish',
    'guj': 'Gujarati',
    'hat': 'Haitian Creole',
    'hau': 'Hausa',
    'heb': 'Hebrew',
    'hin': 'Hindi',
    'hrv': 'Croatian',
    'hun': 'Hungarian',
    'hye': 'Armenian',
    'ibo': 'Igbo',
    'ind': 'Indonesian',
    'isl': 'Icelandic',
    'ita': 'Italian',
    'jpn': 'Japanese',
    'kan': 'Kannada',
    'kat': 'Georgian',
    'khm': 'Khmer',
    'kin': 'Kinyarwanda',
    'kir': 'Kirghiz',
    'kor': 'Korean',
    'kur': 'Kurdish',
    'lao': 'Lao',
    'lav': 'Latvian',
    'lin': 'Lingala',
    'lit': 'Lithuanian',
    'lug': 'Luganda',
    'mal': 'Malayalam',
    'mar': 'Marathi',
    'mkd': 'Macedonian',
    'mlg': 'Malagasy',
    'mon': 'Mongolian',
    'mya': 'Burmese',
    'nde': 'North Ndebele',
    'nep': 'Nepali',
    'nld': 'Dutch',
    'ori': 'Oriya',
    'orm': 'Oromo',
    'pan': 'Panjabi',
    'pol': 'Polish',
    'por': 'Portuguese',
    'prs': 'Dari',
    'pus': 'Pushto',
    'ron': 'Romanian',
    'run': 'Rundi',
    'rus': 'Russian',
    'sin': 'Sinhala',
    'slk': 'Slovak',
    'slv': 'Slovenian',
    'sna': 'Shona',
    'som': 'Somali',
    'sot': 'Sotho',
    'spa': 'Spanish',
    'sqi': 'Albanian',
    'srp': 'Serbian',
    'swa': 'Swahili',
    'swe': 'Swedish',
    'tam': 'Tamil',
    'tel': 'Telugu',
    'tgk': 'Tajik',
    'tha': 'Thai',
    'tir': 'Tigrinya',
    'tur': 'Turkish',
    'twi': 'Twi',
    'ukr': 'Ukrainian',
    'urd': 'Urdu',
    'uzb': 'Uzbek',
    'vai': 'Vai',
    'vie': 'Vietnamese',
    'wol': 'Wolof',
    'xho': 'Xhosa',
    'yor': 'Yoruba',
    'yue': 'Yue Chinese',
    'zho': 'Chinese',
    'zul': 'Zulu'
}